autodeploy/urls.py
from django.conf.urls import url
from django.contrib import admin
import views
urlpatterns = [
    url(r'^stgdep$', views.stgdep, name='stg_dep'),
    url(r'^closestg/(?P<eid>\d)$', views.closestg, name='close_stg'),
    url(r'^gettask/(?P<id>\d+)$', views.getTask, name='get_task'),
    url(r'^ajxgetproj/(?P<id>\d+)$', views.ajxgetproj, name='ajxgetproj'),
    url(r'^posttask$', views.postTask, name='post_task'),
    url(r'getdepresult/(?P<id>\d+)$', views.getDepResult, name='get_dep_result'),
    url(r'^ajxstartdep/(?P<id>\d+)$', views.ajxStartDep, name='ajx_start_dep'),
    url(r'^ajxpushlog/(?P<fid>\d+),(?P<line_num>\d+)$', views.ajxPushLog, name='ajx_push_log'),
    url(r'^ajxdistribute/(?P<tid>\d+),(?P<hid>\d+)$', views.ajxDistribute2Host,name='ajx_distribute_host'),
    url(r'^taskli$', views.taskli, name='task_li'),
    url(r'^projectli$', views.projectli, name='project_li'),
    url(r'^taskdetail/(?P<tid>\d+)$', views.taskDetail, name='task_detail'),
    url(r'^ajxgetlog/(?P<pid>\d+),(?P<hid>\d+),(?P<tid>\d+)$', views.ajxGetLog, name='ajx_get_log'),
    url(r'^ajxloghandle/(?P<pid>\d+),(?P<hid>\d+),(?P<tid>\d+),(?P<line>\d+)$', views.ajxGetLogHandle,name='ajx_handle_log'),
    url(r'^alert_handle/(?P<tid>\d+)$', views.alert_handle, name='alert_handle')
]

online_deploy/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from autodeploy import urls as auto_urls
import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.login, name='login'),
    url(r'^home/$', views.loginHandle, name='home'),
    url(r'^changepass/$', views.changepass, name='changepass'),
    url(r'^changepass_handle/$', views.changepassHandle, name='changepass_handle'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^gotochpass/$', views.gotochpass, name='gotochpass'),
    url(r'^getvalicode/$', views.getvalicode, name='getvalicode'),
    url(r'^chpass/$', views.chpass, name='chpass'),
    url(r'^chpass_handle/$', views.chpassHandle,name='chpass_handle'),

    url(r'^autodeploy/',include(auto_urls,namespace='autodeploy'))
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
	{% load staticfiles %}
	<head>
		<meta charset="utf-8">
		<title>{% block title%}火球网212测试运维平台{% endblock%}</title>
		<meta name="description" content="description">
		<meta name="author" content="DevOOPS">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="{% static 'plugins/bootstrap/bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
		<link href="{% static 'plugins/fancybox/jquery.fancybox.css' %}" rel="stylesheet">
		<link href="{% static 'plugins/fullcalendar/fullcalendar.css' %}" rel="stylesheet">
		<link href="{% static 'plugins/xcharts/xcharts.min.css' %}" rel="stylesheet">
		<link href="{% static 'plugins/select2/select2.css' %}" rel="stylesheet">
		<link href="{% static 'plugins/justified-gallery/justifiedGallery.css' %}" rel="stylesheet">
		<link href="{% static 'css/style_v1.css' %}" rel="stylesheet">
		<link href="{% static 'plugins/chartist/chartist.min.css' %}" rel="stylesheet">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
				<script src="http://getbootstrap.com/docs-assets/js/html5shiv.js"></script>
				<script src="http://getbootstrap.com/docs-assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
<body>
<!--Start Header-->
<div id="screensaver">
	<canvas id="canvas"></canvas>
	<i class="fa fa-lock" id="screen_unlock"></i>
</div>
<div id="modalbox">
	<div class="devoops-modal">
		<div class="devoops-modal-header">
			<div class="modal-header-name">
				<span>Basic table</span>
			</div>
			<div class="box-icons">
				<a class="close-link">
					<i class="fa fa-times"></i>
				</a>
			</div>
		</div>
		<div class="devoops-modal-inner">
		</div>
		<div class="devoops-modal-bottom">
		</div>
	</div>
</div>
<header class="navbar">
	<div class="container-fluid expanded-panel">
		<div class="row">
			<div id="logo" class="col-xs-12 col-sm-2 logo-gpj">
				<a href="/">火球网212运维平台</a>
			</div>
			<div id="top-panel" class="col-xs-12 col-sm-10">
				<div class="row">
					<div class="col-xs-8 col-sm-4">
						<!--<div id="search">
							<input type="text" placeholder="search"/>
							<i class="fa fa-search"></i>
						</div>-->
					</div>
					<div class="col-xs-4 col-sm-8 top-panel-right">
						<ul class="nav navbar-nav pull-right panel-menu">										
							<li class="dropdown">
								<a href="#" class="dropdown-toggle account" data-toggle="dropdown">
									<div class="avatar">
										<img src="{% static 'img/avatar.jpg'%} " class="img-circle" alt="avatar" />
									</div>
									<i class="fa fa-angle-down pull-right"></i>
									<div class="user-mini pull-right">
										<span class="welcome">欢迎,</span>
										<span>{{nick}}</span>
									</div>
								</a>
								<ul class="dropdown-menu">
									<!-- <li>
										<a href="#">
											<i class="fa fa-cog"></i>
											<span>设置</span>
										</a>
									</li> -->
									<li>
										<a href="{% url 'changepass' %}">
											<i class="fa fa-cog"></i>
											<span>修改密码</span>
										</a>
									</li>
									<li>
										<a href="{% url 'logout' %}">
											<i class="fa fa-power-off"></i>
											<span>注销</span>
										</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<!--End Header-->
<!--Start Container-->
<div id="main" class="container-fluid">
	<div class="row">
		<div id="sidebar-left" class="col-xs-2 col-sm-2">
			<ul class="nav main-menu">
				<li>
					<a class="" href="{% url 'autodeploy:stg_dep' %}">
						<i class="fa fa-picture-o"></i>
						 <span class="hidden-xs">我要发布</span>
					</a>
				</li>

                <li>
					<a class="" href="{% url 'autodeploy:task_li' %}">
						<i class="fa fa-bar-chart-o"></i>
						 <span class="hidden-xs">发布统计</span>
					</a>
				</li>

				<li>
					<a class="" href="{% url 'autodeploy:project_li' %}">
						<i class="fa fa-list"></i>
						 <span class="hidden-xs">项目概览</a></span>
					</a>
				</li>


			<!-- 	<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-bar-chart-o"></i>
						<span class="hidden-xs">自动部署</span>
					</a>
					<ul class="dropdown-menu">
						<li></li>
						<li><a class="" href="#">发布统计</a></li>
						<li><a class="" href="{% url 'autodeploy:project_li'%}">项目概览</a></li>
					</ul>
				</li>		 -->	
			</ul>
		</div>
		<!--Start Content-->
		<div id="content" class="col-xs-12 col-sm-10">
		{%block content%} {%endblock%}
		</div>
		<!--End Content-->
	</div>
</div>
<!--End Container-->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--<script src="http://code.jquery.com/jquery.js"></script>-->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/justified-gallery/jquery.justifiedGallery.min.js' %}"></script>
<script src="{% static 'plugins/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'plugins/tinymce/jquery.tinymce.min.js' %}"></script>
<!-- All functions for this theme + document.ready processing -->
<script src="{% static 'js/devoops.js' %}"></script>
{%block footjs%}{%endblock%}
</body>
</html>

templates/changepass.html
{% extends 'base.html' %}
{% block content %}
<div class="box-content">
<form class="form-horizontal bv-form" action="{% url 'changepass_handle' %}" method="post" id="defaultForm" novalidate="novalidate">
{% csrf_token %} 
  <fieldset>
	<legend>修改密码</legend>
		<div class="form-group">
			<label class="col-sm-3 control-label">当前密码</label>
			<div class="col-sm-5">
				<input type="password" name="password" class="form-control" data-original-title="" title="" data-bv-field="password">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">新密码</label>
			<div class="col-sm-5">
				<input type="password" name="newpassword" class="form-control" data-original-title="" title="" data-bv-field="newpassword">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">确认新密码</label>
			<div class="col-sm-5">
				<input type="password" name="confirmpassword" class="form-control" data-original-title="" title="" data-bv-field="confirmpassword">
			</div>
		</div>
		<div style="margin-left:35%">
			<button type="submit" class="btn btn-primary">&nbsp;&nbsp;确 认&nbsp;&nbsp;</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<button type="button" class="btn btn-danger">&nbsp;&nbsp;取 消&nbsp;&nbsp;</button>
		</div>
  </fieldset>
</form>
</div>
{% endblock %}
{%block footjs %}
<script>
$(function(){
	$(".btn-danger").click(function(){
		history.back(-1)
	})
})
</script>
{%endblock%}

templates/chpass.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>HUOQIU</title>
		<meta name="description" content="description">
		<meta name="author" content="Evgeniya">
		<meta name="keyword" content="keywords">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		{% load staticfiles %}
		<link href="{% static 'plugins/bootstrap/bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
		<link href="{% static 'css/style_v1.css' %}" rel="stylesheet">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
				<script src="http://getbootstrap.com/docs-assets/js/html5shiv.js"></script>
				<script src="http://getbootstrap.com/docs-assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
<body>
<div class="container-fluid">
	<div id="page-login" class="row">
		<div class="col-xs-12 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
			<div class="text-right">
				<!--<a href="page_register_v1.html" class="txt-default">Need an account?</a>-->
			</div>
			<div class="box">
			<form method="post" action="{% url 'chpass_handle' %}">
			{% csrf_token %}
				<div class="box-content">
					<div class="text-center">
						<h3 class="page-header">火球密码管理</h3>
					</div>
					<div class="form-group">
						<label class="control-label">用户名</label>
						<input type="text" class="form-control" name="username" />
					</div>
                    <div class="form-group">
						<label class="control-label">邮箱地址</label>
						<input type="text" class="form-control" name="email" />
					</div>
					<div class="form-group">
						<label class="control-label">邮箱验证码</label>
						<input type="text" class="form-control" name="mailcode" />
					</div>
					<div class="form-group">
						<label class="control-label">新密码</label>
						<input type="password" class="form-control" name="newpass" />
					</div>
					<div class="form-group">
						<label class="control-label">确认新密码</label>
						<input type="password" class="form-control" name="confirmpass" />
					</div>
					<div class="text-center">
						<button class="btn btn-primary">修 改</button>
					</div>
				</div>
			</form>
			</div>
		</div>
	</div>
</div>
</body>
</html>

templates/get_task.html
{% extends "base.html" %}
{% block content %}
<div class="col-xs-12 col-sm-8" style="margin-top:30px;">
		<div class="box ui-draggable ui-droppable">
			<div class="box-header">
				<div class="box-name ui-draggable-handle">
					<i class="fa fa-plus-square"></i>
					<span>创建上线任务</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="display: block;">
				<form class="form-horizontal bv-form" action="{% url 'autodeploy:post_task' %}" method="post" id="defaultForm" >
				{% csrf_token %}
				<input type='hidden' name="environment_id" value="{{environment_id}}">
				<button type="submit" class="bv-hidden-submit" style="display: none; width: 0px; height: 0px;"></button>
					<fieldset>
						<legend></legend>

						<div class="form-group">
							<label class="col-sm-3 control-label">项目名称</label>
							<div class="col-sm-5">
								<select class="form-control" id="proj" name="project">

								</select>
							</div>
						</div>


                        <div class="form-group">
							<label class="col-sm-3 control-label">分支名称</label>
							<div class="col-sm-5">
								<input type="text" name="gitbranch" class="form-control" data-original-title="" title="">
							</div>
						</div>

						
					<fieldset>
					<legend></legend>
				    <div class="form-group">
						<label for="form-styles" class="col-sm-2 control-label">上线事由</label>
						<div class="col-sm-10">
								<textarea id="wysiwig_simple" rows="5" class="form-control" data-original-title="" title="" name="content"></textarea>
						</div>
					</div>
					</fieldset>
					<div class="form-group">
						<div class="col-sm-9 col-sm-offset-3">
							<button class="btn btn-primary" type="submit">提交</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}
{% block footjs %}
<script type="text/javascript">
$(function(){
var environment_id = {{environment_id}}
$.get("{% url 'autodeploy:ajxgetproj' environment_id %}",
      function(data){ 
      	if(data){
      		for(var i=0;i<data.length;i++){
      			$('#proj').append("<option value='"+data[i]['pk']+"'>"+data[i]['fields']['shortname']+"</option>");
      		}
      	}
      }, "json");
});
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<div style="margin-top:250px;">
<center><img style="border-radius:900px;" src="{% static 'img/logo2.gif' %}"/></center>
</div>
{% endblock %}

templates/logs.html
<style type="text/css">
html,body{background:#000; color:#090;}
</style>

{% load staticfiles %}
<div style="margin-top:10px;">
<p id='log'></p>
</div>
<script src="/static/plugins/jquery/jquery.min.js"></script>
<script src="/static/plugins/jquery-ui/jquery-ui.min.js"></script>
<script>
$(function(){
var line = {{line}};
var pid = {{pid}};
var hid = {{hid}};
var tid = {{tid}};
console.log(pid,hid,tid,line)
    //var url = 'http://'+location.host + '/autodeploy/ajxloghandle/'+'&pid'+pid+"&hid"+hid+'&line'+line;
    //var ulre='http://'+location.host + '/autodeploy/ajxloghandle/'+pid+'&'+hid+'&'+line;
    //console.log(ulre);
$.ajax({
    url: "{% url 'autodeploy:ajx_handle_log' pid=pid hid=hid tid=tid line=line %}",
    type: 'GET',
    success: function(data){ 
        if(data != 500){
          $('#log').append('<p>'+data+'</p>');
          var t  = setInterval(function(){
              line++;
              var url = "http://"+location.host + '/autodeploy/ajxloghandle/'+pid + ',' + hid + ',' + tid + ',' +line;

             $.ajax({
                url: url,
                type: 'GET',
                success: function(data){
                     if(data != 500){
                         $('#log').append('<p>'+data+'</p>');
                         window.scrollTo(0,document.body.scrollHeight);
                     }else{
                          clearInterval(t);
                     }
                },
                error: function(data) {
                    alert('服务器提出了一个问题，请找运维寻求答案！');
                    return false;
                 }
             });
          },200); 
        }else{
          alert('服务器提出了一个问题，请找运维寻求答案！');
        }
    },
    error: function(data) {
        alert('服务器提出了一个问题，请找运维寻求答案！');
        return false;
    }
});
});

</script>

templates/stg_dep.html
{% extends "base.html" %}
{% block content %}
{% load audep_extras%}
<div class="well" style="margin-top:20px;">
	<p class="lead">预发布环境
	</p>
	<h3 id="grid-options">概况</h3>
	<div class="table-responsive">
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
				    <th>平台名称</th>
					<th>平台编号</th>
					<th>使用情况</th>
					<th>使用人</th>
					<th>开始时间</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			    {% if environments %}
			    {% for en in environments %}
				{% if en.name != 'db01' and en.name != 'db02' %}
				<tr>
					<th>{{ en.name }}</th>
					<td>{{ en.shortname }}</td>
                                    {% if en.status == 0 %}
					<td class="success"><code>{{ en.hstatus }}</code></td>
			            {% else %}
					<td class="danger"><code>{{ en.hstatus }}</code></td>
			            {% endif %}

					<td>{{ en.user }}</td>
					<td>{{ en.usetime | timestamp }}</td>
					{% if en.status == 0 %}
					<td><a href="{% url 'autodeploy:get_task' en.id %}">{{ en.handle | safe}}</a></td>
					{% else %}
                                        <td><a href="{% url 'autodeploy:close_stg' en.id %}">{{ en.handle | safe}}</a></td>
					{% endif %}
				</tr>
				{% endif %}
				{% endfor %}
				{% else %}
				<p>暂无可用的预发平台！</p>
				{% endif %}
				
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

templates/stg_dep_results.html
{% extends "base.html" %}
{% block content %}
{% load audep_extras%}
{% load staticfiles %}
<div class="row" style="margin-top:30px">
	<div class="col-xs-12">
		<div class="box ui-draggable ui-droppable">
			<div class="box-header">
				<div class="box-name ui-draggable-handle">
					<i class="fa fa-table"></i>
					<span>SA for all</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content no-padding">
				<div class="bs-callout">
					<button data-dismiss="alert" class="close">×</button>
					<h4>{{environment.name}}上线</h4>
					<p></p><p></p>
					<p><strong>平台编号：</strong>{{ environment.shortname }}</p>
					<p><strong>项目名称：</strong>{{ project.shortname }}</p>
					<p><strong>分支名称：</strong>{{ gitbranch }}</p>
					<p></p>
					<p></p>
					<div id="proj-build"><i class="fa fa-bullhorn"></i>
					    <p id='build-notify'>项目编译中，请耐心等待...</p>
					    <div id='build-preload' style="position:absolute;">
				          <img alt="preloader" class="devoops-getdata" src="{% static 'img/devoops_getdata.gif' %}">
			            </div>
			        </div>
			        <div id='proj-build-result'></div>
				</div>
				<div id="hosts-dep" style="margin-top:30px;display:none;">
				<h4>上线结果</h4>
				<legend></legend>
				<table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
					<thead>
						<tr>
							<th>主机名</th>
							<th>ip</th>
							<th>状态</th>
							<th>操作</th>
						</tr>
					</thead>
					<tbody>
					{% if hosts %}
					{% for h in hosts %}
						<tr>
							<td>{{ h.hostname }}</td>
							<td>{{ h.ip }}</td>
							<td id="host-{{ h.id }}" class="active"><center><img  src="{% static 'img/progress-b.gif' %}"></center></td>
							<td><a href="{% url 'autodeploy:ajx_get_log' pid=project.id hid=h.id tid=tid%}" target=_blank>查看日志</a></td>
						</tr>
					{% endfor %}
					{% endif %}
					</tbody>
				</table>
				<div class="col-sm-9 col-sm-offset-3" style="margin-top:20px;">
				    <button id='btn-result' class="btn btn-primary" type="button">返回</button>
				</div>
				</div>


			</div>
		</div>
	</div>
</div>
<textarea readonly="readonly" style="margin-top: 20px;clear: both;background-color: #000;color:#fff;font-size: 1em;width: 100%;height:800px; " class="log-container"></textarea>

{% endblock %}
{% block footjs %}
<script type="text/javascript">
$(function(){
	function getOneLineLog(){
		if(!window.intervalGetLog_autoIncrement){
			window.intervalGetLog_autoIncrement = 1;
		}

		$.ajax({
			async:false,
			url: '/autodeploy/ajxpushlog/{{ tid }},'+window.intervalGetLog_autoIncrement,
			type:'get',
			dataType:'json',
			success: function(json){
				if(json.success == 1){
					window.intervalGetLog_autoIncrement+=json.read_num;
					$('.log-container').append(json.data).scrollTop(1000000);
//				}else if(json.success == 2){

				}else{
					if(intervalGetLog){
						window.intervalGetLog_autoIncrement+=json.read_num;
						$('.log-container').append(json.data).scrollTop(1000000);
						$('.log-container').append(json.data).scrollTop(1000000);
						clearInterval(window.intervalGetLog);
					}
				}

			},
			error: function (e){
				if(window.console){
					console.debug(e);
				}
				if(intervalGetLog){
					clearInterval(window.intervalGetLog);
				}
				alert('加载日志失败,请手动加载');
			}
		});

	}

	// 定时拉日志(one line)
	window.intervalGetLog = window.setInterval(function (){getOneLineLog()}, 1000);


$.ajax({
    url: "{% url 'autodeploy:ajx_start_dep' tid %}",
    type: 'GET',
    success: function(data){ 
        if(data == 0){
            $('#build-notify').replaceWith('<code style="color:green;">项目编译成功</code>');
            $('#build-preload').css('display','none');
            $('#hosts-dep').css('display','block');
            {% for host in hosts%}
                $.get("{% url 'autodeploy:ajx_distribute_host' tid=tid hid=host.id %}",
                     function(data){
                     	if(data == 0){
                                $("#host-{{host.id}}").addClass('success');
                     		$("#host-{{host.id}}").html('<code style="color:green;">部署成功</code>');
                     	}else{
                                $("#host-{{host.id}}").addClass('danger');
                     		$("#host-{{host.id}}").html('<code>'+data+'</code>');
                     	}                	      
                 });
            {% endfor %}

        }else{
            $('#build-notify').replaceWith('<code>项目编译失败</code>');
            $('#build-preload').css('display','none');
            $('#proj-build-result').html("<pre style='background-color:#ededed;border:none;'>"+data+"</pre>")
        }
    },
    error: function(data) {

//		$.ajax({
//			url: "/autodeploy/alert_handle/{{ tid }}",
//			type: 'GET',
//			success: function (data) {
//				if(data){
//					alert(data);
//				}
//				else
//				alert('服务器提出了一个问题，请找运维寻求答案！'); //or whatever
//			}
//		});


		alert('服务器提出了一个问题，请找运维寻求答案！'); //or whatever

        return false;
    }
});

// $.get("{% url 'autodeploy:ajx_start_dep' tid %}",
//       function(data){ 
//         if(data == 0){
//             $('#build-notify').replaceWith('<code style="color:green;">项目编译成功</code>');
//             $('#build-preload').css('display','none');
//             $('#hosts-dep').css('display','block');
//             {% for host in hosts%}
//                 $.get("{% url 'autodeploy:ajx_distribute_host' tid=tid hid=host.id %}",
//                      function(data){
//                      	if(data == 0){
//                                 $("#host-{{host.id}}").addClass('success');
//                      		$("#host-{{host.id}}").html('<code style="color:green;">部署成功</code>');
//                      	}else{
//                                 $("#host-{{host.id}}").addClass('danger');
//                      		$("#host-{{host.id}}").html('<code>'+data+'</code>');
//                      	}                	      
//                  });
//             {% endfor %}

//         }else{
//             $('#build-notify').replaceWith('<code>项目编译失败</code>');
//             $('#build-preload').css('display','none');
//             $('#proj-build-result').html("<pre style='background-color:#ededed;border:none;'>"+data+"</pre>")
//         }
//       });
$('#btn-result').click(function(){
	window.location.href="/autodeploy/stgdep";
})

});


</script>
{% endblock %}

templates/task_li.html
{% extends "base.html" %}
{% block content %}
{% load audep_extras%}
<div class="well" style="margin-top:20px;">
	<p class="lead">发布列表
	</p>
	<div class="table-responsive">
	 {% if tasks %}
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
				    <th>任务编号</th>
					<th>发布人</th>
					<th>项目名称</th>
					<th>git分支</th>
					<th>平台编号</th>
					<th>发布时间</th>
					<th>发布状态</th>
				</tr>
			</thead>
			<tbody>
			   
			    {% for ta in tasks %}
				<tr>
					<th><a href="{% url 'autodeploy:task_detail' ta.id %}">{{ ta.id }}</a></th>
					<td>{{ ta.nick }}</td>
					<td>{{ ta.project.shortname }}</td>
					<td>{{ ta.gitbranch }}</td>					
					<td>{{ ta.environment.shortname }}</td>
					<td>{{ ta.createtime | timestamp }}</td>	
                    {% if ta.status == 0 %}
					<td class="success"><code>发布成功</code></td>
			        {% else %}
					<td class="danger"><code>发布失败</code></td>
			        {% endif %}
				
				</tr>
				{% endfor %}
				{% else %}
				<p>你还未发布过项目，来早了！</p>
				{% endif %}
				
			</tbody>
		</table>
	</div>

    <div class="row">		
	<div class="col-xs-12">
		<ul class="pagination pagination-lg">
		{% if tasks.has_previous %}
			<li><a href="?page={{ tasks.previous_page_number }}">«</a></li>
		{% endif %}
     
        {% for i in tasks.paginator.page_range %}
            {% if tasks.number == i%}
			<li class="active"><a href="?page={{i}}">{{i}}</a></li>
			{% else %}
			<li class=""><a href="?page={{i}}">{{i}}</a></li>
            {% endif %}
        {%endfor%}

		{% if tasks.has_next %}
			<li><a href="?page={{ tasks.next_page_number }}">»</a></li>
        {% endif %}		
		</ul>
	</div>
</div>

</div>
{% endblock %}